# File: params.yaml

# Experiment basics parameters
basics:
  experiment_name: introvert_extrovert_classification
  kaggle: true
  problem_type: classification #classification or regression
  classes:
    - Extrovert
    - Introvert

# Data Preprocessing parameters
data_preprocessing:
  data_path: data/train.csv
  target_column: Personality
  sample_identificator_column: id

# Model parameters
model:
  name: xgboost
  hyperparameters:
    objective: binary:logistic
    eval_metric: logloss
    use_label_encoder: False
    random_state: 42
    n_estimators: 100
    max_depth: 3
    learning_rate: 0.1
    colsample_bytree: 0.5
    subsample: 0.5
  

# Training parameters
training:
  first_training: false
  last_training: false
  use_validation: true
  validation_split: 0.2
  early_stopping_rounds: 10
  verbose: 1
  epochs: 10

# Evaluation parameters
evaluation:
  test_data_path: data/test.csv
  metrics: accuracy